#persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: my-disk-claim
spec:
 resources:
  requests:
   storage: 200Mi
 accessModes:
  - ReadWriteOnce
 storageClassName: manual 
