apiVersion: v1
kind: Pod
metadata:
 name: dis-pod
 labels:
  app: nginx
  tier: dev
spec:
 containers:
  - name: dis-container
    image: samratisp.azurecr.io/dis-private
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
 imagePullSecrets:
  - name: samrat-azure-pvt-reg
 hostNetwork: true
 dnsPolicy: ClusterFirstWithHostNet
