apiVersion: v1
kind: ReplicationController
metadata:
 name: dis-pod
spec:
 replicas: 3
 selector:
  app: dis-app
 template:
  metadata:
   name: dis-pod
   labels:
    app: dis-app
  spec:
   containers:
    - name: dis-container
      image: samratisp.azurecr.io/dis-private
    # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
   imagePullSecrets:
    - name: samrat-azure-pvt-reg
   hostNetwork: true
   dnsPolicy: ClusterFirstWithHostNet

